name: Build in Dokcer

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v2
       - name: Build the Docker image
         run: docker build . --file Dockerfile
