name: Build in Dokcer

on: workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      # 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      # 设置qemu来编译多个平台的镜像
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # 设置buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 编译并且推送到dockerhub
      - name: 构建并推送到 Dockerhub 镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Dockerfile 位置
          platforms: linux/amd64
