name: Go

on: workflow_dispatch

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Build
      run: |
        go build -v ./...
        go build -tags=bindata -mod=vendor
